# -*- coding: utf-8 -*-

kanmusuIndex = dict()

# Official ID
kanmusuIndex["1"]      = ("長門", "")
kanmusuIndex["2"]      = ("陸奥", "")
kanmusuIndex["3"]      = ("伊勢", "")
kanmusuIndex["4"]      = ("日向", "")
kanmusuIndex["5"]      = ("雪風", "")
kanmusuIndex["6"]      = ("赤城", "")
kanmusuIndex["7"]      = ("加賀", "")
kanmusuIndex["8"]      = ("蒼龍", "")
kanmusuIndex["9"]      = ("飛龍", "")
kanmusuIndex["10"]     = ("島風", "")
kanmusuIndex["11"]     = ("吹雪", "")
kanmusuIndex["12"]     = ("白雪", "")
kanmusuIndex["13"]     = ("初雪", "")
kanmusuIndex["14"]     = ("深雪", "")
kanmusuIndex["15"]     = ("叢雲", "")
kanmusuIndex["16"]     = ("磯波", "")
kanmusuIndex["17"]     = ("綾波", "")
kanmusuIndex["18"]     = ("敷波", "")
kanmusuIndex["19"]     = ("大井", "")
kanmusuIndex["20"]     = ("北上", "")
kanmusuIndex["21"]     = ("金剛", "")
kanmusuIndex["22"]     = ("比叡", "")
kanmusuIndex["23"]     = ("榛名", "")
kanmusuIndex["24"]     = ("霧島", "")
kanmusuIndex["25"]     = ("鳳翔", "")
kanmusuIndex["26"]     = ("扶桑", "")
kanmusuIndex["27"]     = ("山城", "")
kanmusuIndex["28"]     = ("天龍", "")
kanmusuIndex["29"]     = ("龍田", "")
kanmusuIndex["30"]     = ("龍驤", "")
kanmusuIndex["31"]     = ("睦月", "")
kanmusuIndex["32"]     = ("如月", "")
kanmusuIndex["33"]     = ("皐月", "")
kanmusuIndex["34"]     = ("文月", "")
kanmusuIndex["35"]     = ("長月", "")
kanmusuIndex["36"]     = ("菊月", "")
kanmusuIndex["37"]     = ("三日月", "")
kanmusuIndex["38"]     = ("望月", "")
kanmusuIndex["39"]     = ("球磨", "")
kanmusuIndex["40"]     = ("多摩", "")
kanmusuIndex["41"]     = ("木曾", "")
kanmusuIndex["42"]     = ("長良", "")
kanmusuIndex["43"]     = ("五十鈴", "")
kanmusuIndex["44"]     = ("名取", "")
kanmusuIndex["45"]     = ("由良", "")
kanmusuIndex["46"]     = ("川内", "")
kanmusuIndex["47"]     = ("神通", "")
kanmusuIndex["48"]     = ("那珂", "")
kanmusuIndex["49"]     = ("千歳", "")
kanmusuIndex["50"]     = ("千代田", "")
kanmusuIndex["51"]     = ("最上", "")
kanmusuIndex["52"]     = ("古鷹", "")
kanmusuIndex["53"]     = ("加古", "")
kanmusuIndex["54"]     = ("青葉", "")
kanmusuIndex["55"]     = ("妙高", "")
kanmusuIndex["56"]     = ("那智", "")
kanmusuIndex["57"]     = ("足柄", "")
kanmusuIndex["58"]     = ("羽黒", "")
kanmusuIndex["59"]     = ("高雄", "")
kanmusuIndex["60"]     = ("愛宕", "")
kanmusuIndex["61"]     = ("摩耶", "")
kanmusuIndex["62"]     = ("鳥海", "")
kanmusuIndex["63"]     = ("利根", "")
kanmusuIndex["64"]     = ("筑摩", "")
kanmusuIndex["65"]     = ("飛鷹", "")
kanmusuIndex["66"]     = ("隼鷹", "")
kanmusuIndex["67"]     = ("朧", "")
kanmusuIndex["68"]     = ("曙", "")
kanmusuIndex["69"]     = ("漣", "")
kanmusuIndex["70"]     = ("潮", "")
kanmusuIndex["71"]     = ("暁", "")
kanmusuIndex["72"]     = ("響", "")
kanmusuIndex["73"]     = ("雷", "")
kanmusuIndex["74"]     = ("電", "")
kanmusuIndex["75"]     = ("初春", "")
kanmusuIndex["76"]     = ("子日", "")
kanmusuIndex["77"]     = ("若葉", "")
kanmusuIndex["78"]     = ("初霜", "")
kanmusuIndex["79"]     = ("白露", "")
kanmusuIndex["80"]     = ("時雨", "")
kanmusuIndex["81"]     = ("村雨", "")
kanmusuIndex["82"]     = ("夕立", "")
kanmusuIndex["83"]     = ("五月雨", "")
kanmusuIndex["84"]     = ("涼風", "")
kanmusuIndex["85"]     = ("朝潮", "")
kanmusuIndex["86"]     = ("大潮", "")
kanmusuIndex["87"]     = ("満潮", "")
kanmusuIndex["88"]     = ("荒潮", "")
kanmusuIndex["89"]     = ("霰", "")
kanmusuIndex["90"]     = ("霞", "")
kanmusuIndex["91"]     = ("陽炎", "")
kanmusuIndex["92"]     = ("不知火", "")
kanmusuIndex["93"]     = ("黒潮", "")
kanmusuIndex["94"]     = ("祥鳳", "")
kanmusuIndex["95"]     = ("千歳改", "")
kanmusuIndex["96"]     = ("千代田改", "")
kanmusuIndex["97"]     = ("大井改", "")
kanmusuIndex["98"]     = ("北上改", "")
kanmusuIndex["99"]     = ("千歳甲", "")
kanmusuIndex["100"]    = ("千代田甲", "")
kanmusuIndex["101"]    = ("最上改", "")
kanmusuIndex["102"]    = ("伊勢改", "")
kanmusuIndex["103"]    = ("日向改", "")
kanmusuIndex["104"]    = ("千歳航", "")
kanmusuIndex["105"]    = ("千代田航", "")
kanmusuIndex["106"]    = ("翔鶴", "")
kanmusuIndex["107"]    = ("瑞鶴", "")
kanmusuIndex["108"]    = ("瑞鶴改", "")
kanmusuIndex["109"]    = ("鬼怒", "")
kanmusuIndex["110"]    = ("阿武隈", "")
kanmusuIndex["111"]    = ("夕張", "")
kanmusuIndex["112"]    = ("瑞鳳", "")
kanmusuIndex["113"]    = ("瑞鳳改", "")
kanmusuIndex["114"]    = ("大井改二", "")
kanmusuIndex["115"]    = ("北上改二", "")
kanmusuIndex["116"]    = ("三隈", "")
kanmusuIndex["117"]    = ("三隈改", "")
kanmusuIndex["118"]    = ("初風", "")
kanmusuIndex["119"]    = ("舞風", "")
kanmusuIndex["120"]    = ("衣笠", "")
kanmusuIndex["121"]    = ("千歳航改二", "")
kanmusuIndex["122"]    = ("千代田航改二", "")
kanmusuIndex["123"]    = ("伊19", "")
kanmusuIndex["124"]    = ("鈴谷", "")
kanmusuIndex["125"]    = ("熊野", "")
kanmusuIndex["126"]    = ("伊168", "")
kanmusuIndex["127"]    = ("伊58", "")
kanmusuIndex["128"]    = ("伊8", "")
kanmusuIndex["129"]    = ("鈴谷改", "")
kanmusuIndex["130"]    = ("熊野改", "")
kanmusuIndex["131"]    = ("大和", "")
kanmusuIndex["132"]    = ("秋雲", "")
kanmusuIndex["133"]    = ("夕雲", "")
kanmusuIndex["134"]    = ("巻雲", "")
kanmusuIndex["135"]    = ("長波", "")
kanmusuIndex["136"]    = ("大和改", "")
kanmusuIndex["137"]    = ("阿賀野", "")
kanmusuIndex["138"]    = ("能代", "")
kanmusuIndex["139"]    = ("矢矧", "")
kanmusuIndex["140"]    = ("酒匂", "")
kanmusuIndex["141"]    = ("五十鈴改二", "")
kanmusuIndex["142"]    = ("衣笠改二", "")
kanmusuIndex["143"]    = ("武蔵", "")
kanmusuIndex["144"]    = ("夕立改二", "")
kanmusuIndex["145"]    = ("時雨改二", "")
kanmusuIndex["146"]    = ("木曾改二", "")
kanmusuIndex["147"]    = ("Верный", "")
kanmusuIndex["148"]    = ("武蔵改", "")
kanmusuIndex["149"]    = ("金剛改二", "")
kanmusuIndex["150"]    = ("比叡改二", "")
kanmusuIndex["151"]    = ("榛名改二", "")
kanmusuIndex["152"]    = ("霧島改二", "")
kanmusuIndex["153"]    = ("大鳳", "")
kanmusuIndex["154"]    = ("香取", "")
kanmusuIndex["155"]    = ("伊401", "")
kanmusuIndex["156"]    = ("大鳳改", "")
kanmusuIndex["157"]    = ("龍驤改二", "")
kanmusuIndex["158"]    = ("川内改二", "")
kanmusuIndex["159"]    = ("神通改二", "")
kanmusuIndex["160"]    = ("那珂改二", "")
kanmusuIndex["161"]    = ("あきつ丸", "")
kanmusuIndex["163"]    = ("まるゆ", "")
kanmusuIndex["164"]    = ("弥生", "")
kanmusuIndex["165"]    = ("卯月", "")
kanmusuIndex["166"]    = ("あきつ丸改", "")
kanmusuIndex["167"]    = ("磯風", "")
kanmusuIndex["168"]    = ("浦風", "")
kanmusuIndex["169"]    = ("谷風", "")
kanmusuIndex["170"]    = ("浜風", "")
kanmusuIndex["171"]    = ("Bismarck", "")
kanmusuIndex["172"]    = ("Bismarck改", "")
kanmusuIndex["173"]    = ("Bismarck zwei", "")
kanmusuIndex["174"]    = ("Z1", "")
kanmusuIndex["175"]    = ("Z3", "")
kanmusuIndex["176"]    = ("Prinz Eugen", "")
kanmusuIndex["177"]    = ("Prinz Eugen改", "")
kanmusuIndex["178"]    = ("Bismarck drei", "")
kanmusuIndex["179"]    = ("Z1 zwei", "")
kanmusuIndex["180"]    = ("Z3 zwei", "")
kanmusuIndex["181"]    = ("天津風", "")
kanmusuIndex["182"]    = ("明石", "")
kanmusuIndex["183"]    = ("大淀", "")
kanmusuIndex["184"]    = ("大鯨", "")
kanmusuIndex["185"]    = ("龍鳳", "")
kanmusuIndex["186"]    = ("時津風", "")
kanmusuIndex["187"]    = ("明石改", "")
kanmusuIndex["188"]    = ("利根改二", "")
kanmusuIndex["189"]    = ("筑摩改二", "")
kanmusuIndex["190"]    = ("龍鳳改", "")
kanmusuIndex["191"]    = ("妙高改二", "")
kanmusuIndex["192"]    = ("那智改二", "")
kanmusuIndex["193"]    = ("足柄改二", "")
kanmusuIndex["194"]    = ("羽黒改二", "")
kanmusuIndex["195"]    = ("綾波改二", "")
kanmusuIndex["196"]    = ("飛龍改二", "")
kanmusuIndex["197"]    = ("蒼龍改二", "")
kanmusuIndex["201"]    = ("雲龍", "")
kanmusuIndex["202"]    = ("天城", "")
kanmusuIndex["204"]    = ("初春改二", "")
kanmusuIndex["205"]    = ("春雨", "")
kanmusuIndex["206"]    = ("雲龍改", "")
kanmusuIndex["207"]    = ("潮改二", "")
kanmusuIndex["208"]    = ("隼鷹改二", "")
kanmusuIndex["209"]    = ("早霜", "")
kanmusuIndex["210"]    = ("清霜", "")
kanmusuIndex["211"]    = ("扶桑改二", "")
kanmusuIndex["212"]    = ("山城改二", "")
kanmusuIndex["213"]    = ("朝雲", "")
kanmusuIndex["214"]    = ("山雲", "")
kanmusuIndex["215"]    = ("野分", "")
kanmusuIndex["216"]    = ("古鷹改二", "")
kanmusuIndex["219"]    = ("初霜改二", "")
kanmusuIndex["221"]    = ("秋月", "")
kanmusuIndex["225"]    = ("朝霜", "")
kanmusuIndex["226"]    = ("吹雪改二", "")
kanmusuIndex["227"]    = ("鳥海改二", "")
kanmusuIndex["228"]    = ("摩耶改二", "")
kanmusuIndex["229"]    = ("天城改", "")
kanmusuIndex["231"]    = ("U-511", "")
kanmusuIndex["236"]    = ("呂500", "")

# User defeined ID


kanmusuIndex["301"]    = ("吹雪改", "")
kanmusuIndex["309"]    = ("金剛改", "")
kanmusuIndex["312"]    = ("霧島改", "")
kanmusuIndex["313"]    = ("天龍改", "")
kanmusuIndex["314"]    = ("龍田改", "")
kanmusuIndex["316"]    = ("多摩改", "")
kanmusuIndex["317"]    = ("木曾改", "")
kanmusuIndex["319"]    = ("五十鈴改", "")
kanmusuIndex["322"]    = ("川内改", "")
kanmusuIndex["323"]    = ("神通改", "")
kanmusuIndex["324"]    = ("那珂改", "")
kanmusuIndex["334"]    = ("暁改", "akatuki")
kanmusuIndex["335"]    = ("響改", "hibiki")
kanmusuIndex["336"]    = ("雷改", "kaminari")
kanmusuIndex["337"]    = ("電改", "denchan")
kanmusuIndex["371"]    = ("摩耶改", "")
kanmusuIndex["377"]    = ("赤城改", "akagi")
kanmusuIndex["386"]    = ("扶桑改", "")
kanmusuIndex["387"]    = ("山城改", "")
kanmusuIndex["389"]    = ("鬼怒改", "")
kanmusuIndex["390"]    = ("阿武隈改", "")

# kanmusuIndex[""]    = ("", "")



def get_ship_name(id):
    name = kanmusuIndex.get(str(id), None)
    if name is not None:
        name = name[0]
    return name

def get_ship_key(nick_name):
    found = False
    for key in kanmusuIndex:
        if kanmusuIndex[key][1] == nick_name:
            found = key
            break
    print "[get_ship_key] found = ", found
    return found


questIndex = dict()

"""
# 每日
201 = 敵艦隊を撃破せよ！
questIndex['403'] = '「遠征」を１０回成功させよう！'
303 = 「演習」で練度向上！
402 = 「遠征」を３回成功させよう！
503 = 艦隊大整備！
605 = 新装備「開発」指令
606 = 新造艦「建造」指令
607 = 装備「開発」集中強化！
608 = 艦娘「建造」艦隊強化！
702 = 艦の「近代化改修」を実施せよ！

# 每週
questIndex['302'] = '大規模演習'
213 = 海上通商破壊作戦
214 = あ号作戦
220 = い号作戦


256 = 「潜水艦隊」出撃せよ！

# 單發
114 = 「南雲機動部隊」を編成せよ！
118 = 「金剛」型による高速戦艦部隊を編成せよ！
121 = 「第四戦隊」を編成せよ！
128 = 「第六戦隊」を編成せよ！
146 = 改修工廠を準備せよ！
272 = 「改装防空重巡」出撃せよ！
275 = 抜錨！「第十八戦隊」
"""

